# For full config options, check the docs:
#    docs.serverless.com

service: zoom-webhook-serverless

resources:
  Resources:
    EventsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: zoomEvents
        VisibilityTimeout: 30
package:
  exclude:
    - node_modules/**
    - .idea
    - package.json
    - package-lock.json
    - .gitignore
    - serverless.yml

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

  environment:
    eventsQueue:
      Ref: EventsQueue
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource:
        Fn::GetAtt: [ EventsQueue, Arn ]

functions:
  hello:
    handler: handler.hello
    events:
      - http: POST /add
